name: fake_model_generator
description: A tool to generate fake model factories for Dart/Flutter projects.
version: 0.1.0
environment:
  sdk: ">=3.0.0 <=3.19.3"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^6.5.0
  faker: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.11
  test: ^1.16.0
